### PR TITLE
Api call tests

### LINKED ISSUE #61: Test SignUp

### PR DESCRIPTION
**Pull request by GraySmith00**
- [x] Wrote Tests
- [ ] Implemented 
- [ ] Reviewed

# Necessary checkmarks:

- [x] All Tests are Passing
- [x] The code will run locally

## Type of change
- [ ] New feature 
- [ ] Bug Fix
- [ ] Refactor

# Implements/Fixes:

* Worked on OffersContainer tests
* Worked on EditOfferModal tests
* Worked on SignUp tests
* Worked on backend
* Worked on RecentOffers tests

closes #61 #58 #52 #60 

# Check the correct boxes

- [ ] This broke nothing
- [x] This broke some stuff
- [ ] This broke everything

# Testing Changes
- [ ] No Tests have been changed
- [x] Some Tests have been changed
- [ ] All of the Tests have been changed(Please describe what in the world happened)

# Checklist:

- [x] My code has no unused/commented out code
- [x] I have reviewed my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have fully tested my code

# Please Include a link to a gif of your feelings about this branch

### CODE REVIEW

**Comment by TFisch** [comment]
hmmm seems to be some conflicts here...

**Comment by GraySmith00** [comment]
hah yup, I'm gonna need to resolve those

**Comment by GraySmith00** [comment]
Resolved the conflicts, it was easy, just the mockData and the SignUp test. Hopefully Travis will be a happy camper now

**Comment by GraySmith00** [comment]
don't merge yet, I'm gonna add the RecentOffers tests and try to make Travis happy

**Comment by TFisch** [comment]
ok, sounds good!

**Comment by TFisch** [comment]
Looks like the dynamic changing date is throwing off the snapshots...

**Comment by TFisch** [comment]
looks great!

**Pull request merged**
